[package]
name = "rust_ntdirect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"

[build]
rustc-link-search = "C:/Windows/SysWOW64"
rustc-link-lib = "NtDirect.dll"
linker = "gcc"